version: '2.1'


job_defaults: &job_defaults
  filters:
    tags:
      only: /.*/


executors:
  go:
    docker:
      - image: circleci/golang:1.16
  python:
    docker:
      - image: circleci/python:3


jobs:
  test:
    executor: go
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            gotestsum --junitfile unit-tests.xml
            make save-coverage-report
      - run:
          name: Get test coverage
          command: |
            go test -race -coverprofile=coverage.txt -covermode=atomic  -v ./...
            bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: unit-tests.xml
      - store_artifacts:
          path: unit-tests.xml
      - store_artifacts:
          path: coverage.html

  build:
    executor: go
    steps:
      - checkout
      - run:
          name: Build binaries
          command: make build
      - persist_to_workspace:
          root: ./
          paths:
            - dist/

  github_release:
    executor: go
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Create github release
          command: |
            go get github.com/github-release/github-release
            git config user.name $CIRCLE_PROJECT_USERNAME
            github-release release \
                --user $CIRCLE_PROJECT_USERNAME \
                --repo $CIRCLE_PROJECT_REPONAME \
                --tag $CIRCLE_TAG \
                --name "Release $CIRCLE_TAG"
            for filename in dist/*
            do
                github-release upload \
                  --replace \
                  --user $CIRCLE_PROJECT_USERNAME \
                  --repo $CIRCLE_PROJECT_REPONAME \
                  --tag $CIRCLE_TAG \
                  --name "$(basename "$filename")" \
                  --file $filename
            done

  update_homebrew_formula:
    executor: python
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Create new Homebrew formula
          command: |
            git clone https://${GITHUB_TOKEN}@github.com/timo-reymann/homebrew-deterministic-zip.git
            cd homebrew-deterministic-zip

            python3 ./generate.py \
              --version $CIRCLE_TAG \
              --sha256-mac $(<../dist/deterministic-zip_darwin-amd64.sha256)
            git config --global user.name "CircleCI"
            git config --global user.email no-reply@circleci.com
            git add .
            git commit -m "chore: Update formula for version $CIRCLE_TAG" || true
            git push

workflows:
  version: 2
  build:
    jobs:
      - test:
          <<: *job_defaults

      - build:
          <<: *job_defaults
          requires:
            - test

      - github_release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - build

      - update_homebrew_formula:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - github_release
